sdk upgrade
UttamPanchasara/PDF-Generator pull request #25
Opened 2024-07-17 11:31 UTC by mcanikhilprajapati

please merge n test and update version 
- I have updated lib to support SDK 34

2024-08-12 08:54 UTC, UttamPanchasara requested changes
Make necessary changes!

2024-08-12 08:54 UTC, UttamPanchasara commented on pdfgenerator/src/main/java/com/uttampanchasara/pdfgenerator/CreatePdf.kt
> +        this.mPdfFilePath = mContext.getExternalFilesDir(null)!!.absolutePath + "/" + pdfFilePath
Absolute Path is input which should not be changed

2024-08-12 08:54 UTC, UttamPanchasara commented on pdfgenerator/build.gradle
> +//}
Revert this change

2024-08-12 08:54 UTC, UttamPanchasara commented on app/src/main/java/com/uttampanchasara/pdf/MainActivity.kt
> +            .setFilePath("MyPdf")
This is an example, No need to add specific path value. revert this

2025-12-25 15:42 UTC, UttamPanchasara commented
@mcanikhilprajapati  Thanks for raising PR!. I have done the changes and just Published the latest version 2.0.0.

Not merging your PR for now, since have done changes in codebase and some new attributes as well, Please check!!

2025-12-25 15:42 UTC, closed without merging

2025-12-31 06:26 UTC, mcanikhilprajapati commented
Thanks a lot for upgrading this library.
I’d be happy to contribute any changes or improvements needed in the future.